[package]
name = "device"
version = "0.1.0"
authors = ["123shang60 <616761475@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_setters    = "0.1"
